# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: TEST

on:
  pull_request:
    branches: [ test ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: check reivew state
      env: 
        review_state: ${{ github.event.pull_request_review.review.state }}
      run: |
        echo $review_state
    - name: Install dependencies
      run: |
        python -m pip install --user --upgrade pip
        python -m pip install --user -r tests/requirements.txt
        python setup.py install --force --user
    - name: Test with pytest
      run: |
        export PATH=/home/docker/.local/bin:$PATH
        pytest -v -n auto tests/test_others --url $BAI_URL --token $BAI_TOKEN
        pytest -v -n auto tests/test_function --url $BAI_URL --token $BAI_TOKEN