# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: TEST

on:
  pull_request:
    branches: [ test ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Install dependencies
      run: |
        pwd
        ls
        id
        python3 -m pip install --upgrade pip
        python3 -m pip install -r tests/requirements.txt
        python3 setup.py install --force
    - name: Test with pytest
      run: |
        pytest -v -n auto tests/test_cli --url $BAI_URL --token $BAI_TOKEN
        pytest -v -n auto tests/test_function --url $BAI_URL --token $BAI_TOKEN